#if !canImport(ObjectiveC)
import XCTest

extension AsyncDNSResolverTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AsyncDNSResolverTests = [
        ("test_concurrency", test_concurrency),
        ("test_queryAAAA", test_queryAAAA),
        ("test_queryA", test_queryA),
        ("test_queryCNAME", test_queryCNAME),
        ("test_queryMX", test_queryMX),
        ("test_queryNAPTR", test_queryNAPTR),
        ("test_queryNS", test_queryNS),
        ("test_queryPTR", test_queryPTR),
        ("test_querySOA", test_querySOA),
        ("test_querySRV", test_querySRV),
        ("test_queryTXT", test_queryTXT),
    ]
}

extension ChannelTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ChannelTests = [
        ("test_AresChannel", test_AresChannel),
    ]
}

extension ErrorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ErrorTests = [
        ("test_initFromCode", test_initFromCode),
    ]
}

extension OptionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OptionsTests = [
        ("test_AresOptions_socketStateCallback", test_AresOptions_socketStateCallback),
        ("test_Flags", test_Flags),
        ("test_Options_rotateFalse", test_Options_rotateFalse),
        ("test_Options_rotateNotSet", test_Options_rotateNotSet),
        ("test_Options_rotateTrue", test_Options_rotateTrue),
        ("test_OptionsToAresOptions", test_OptionsToAresOptions),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AsyncDNSResolverTests.__allTests__AsyncDNSResolverTests),
        testCase(ChannelTests.__allTests__ChannelTests),
        testCase(ErrorTests.__allTests__ErrorTests),
        testCase(OptionsTests.__allTests__OptionsTests),
    ]
}
#endif
